# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://joncanady.com
title: joncanady.com
subtitle: Wherein Writing Occurs
author: Jon Canady
simple_search: http://google.com/search

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: jon@joncanady.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Technically the blog is at /blog/...
# but if this changes all the Google permalinks break. 
root: /
port: 4000
permalink: /:year/:month/:day/:title
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: categories
markdown: rdiscount
pygments: true

paginate: 10 # Posts per page on the blog index
recent_posts: 5 # Posts in the sidebar Recent Posts section

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Twitter
twitter_user: joncanady
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google Plus
google_plus_one: true
google_plus_one_size: medium

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:

# Google Analytics
google_analytics_tracking_id: UA-7193784-a
